run:
	java lib/Main/Remover

build:
	javac -d . src/CkSumStore.java src/FeedbackForm.java src/CRC_CheckSum.java src/LogCreate.java src/ScanPanel.java src/Home.java src/LogPanel.java src/Selectoption.java src/SearchPanel.java ./Remover.java
